services:
  db:
    container_name: e_commerce_db
    image: postgres:latest
    restart: always
    env_file:
       - .env
    ports:
      - ${PGPORT}:${PGPORT}
  backend:
    container_name: e_commerce_backend
    command: python3 ./app.py
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - ${BACKEND_SERVER_PORT}:${BACKEND_SERVER_PORT}
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - db
